sgdOptions:
    alpha: 0.1 # learning rate
    max_iter  : 500 # number of iterations for the local SGD per communication rounds
    lambda_: 0.01 # Regularization parameter lambda
    tolerance: 0.00001
    L: 0.1 #Lot size in DPSGD


labelColumn: null
communication_rounds: 5 # number of times the local models get aggregated and then broadcasted
dpMode: # list, different modes:
        #   dpSgd - applies the DP-SGD algorithm
        #   dpClient - applies DP to models sent by clients to the coordinator
        #   null - no dp at all
        - null
dpOptions:
    epsilon: 0.9
    delta: 0.0 # if 0 laplace noise, else gauss noise
    C: 1 # norm bound
